/* generated by Svelte v3.58.0 */
import { create_ssr_component, each, escape } from "svelte/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { posts } = $$props;
	let count = 0;

	function handleClick() {
		count = count + 1;
	}

	if ($$props.posts === void 0 && $$bindings.posts && posts !== void 0) $$bindings.posts(posts);

	return `<button>count: ${escape(count)}</button>
<h1>All posts</h1>
${each(posts, post => {
		return `<h2><a href="${"/post/view/" + escape(post.id, true)}">${escape(post.title)}</a></h2>`;
	})}
<h3><a href="/add">add post</a></h3>`;
});

export default Component;